### ISSUE TITLE
Empty string error

### ISSUE THREAD

**Issue by johnb30** [openeventdata/petrarch#53]
Error Andy received when trying to process some data. Seems to indicate events with empty strings are being stored in the output dictionaries. 

```
petrarch parse -i all-stories-parsed2.csv -o output.txt -P -c new_actor_config.ini

Traceback (most recent call last):
  File "//anaconda/bin/petrarch", line 9, in <module>
    load_entry_point('petrarch==0.01a', 'console_scripts', 'petrarch')()
  File "/Users/caerusdata/OEDA/devstuff/petrarch/petrarch/petrarch.py", line 2819, in main
    run(paths, cli_args.output, cli_args.parsed)
  File "/Users/caerusdata/OEDA/devstuff/petrarch/petrarch/petrarch.py", line 2859, in run
    PETRwriter.write_events(updated_events, out_file)
  File "/Users/caerusdata/OEDA/devstuff/petrarch/petrarch/PETRwriter.py", line 30, in write_events
    filtered_events = utilities.story_filter(story_dict, key)
  File "/Users/caerusdata/OEDA/devstuff/petrarch/petrarch/utilities.py", line 86, in story_filter
    if event[0][0] != '-' and event[1][0] != '-':
IndexError: string index out of range
```

**Comment by johnb30** [comment]
Addressed (I think...) by later updates.
