### ISSUE TITLE
Verb dictionary reader

### ISSUE THREAD

**Issue by johnb30** [openeventdata/petrarch#55]
@ahalterman found a bug when reading in verb dictionaries. 

```
Verb dictionary: /Users/caerusdata/OEDA/Dictionaries/CAMEO.verbpatterns.txt
Traceback (most recent call last):
  File "//anaconda/bin/petrarch", line 9, in <module>
    load_entry_point('petrarch==0.01a', 'console_scripts', 'petrarch')()
  File "/Users/caerusdata/OEDA/devstuff/petrarch/petrarch/petrarch.py", line 2804, in main
    read_dictionaries()
  File "/Users/caerusdata/OEDA/devstuff/petrarch/petrarch/petrarch.py", line 2830, in read_dictionaries
    PETRreader.read_verb_dictionary(verb_path)
  File "/Users/caerusdata/OEDA/devstuff/petrarch/petrarch/PETRreader.py", line 1046, in read_verb_dictionary
    curcode = primarycode
UnboundLocalError: local variable 'primarycode' referenced before assignment
```

**Comment by johnb30** [comment]
Hasn't presented since August. Closing for now.
