### ISSUE TITLE
Processing bug

### ISSUE THREAD

**Issue by johnb30** [openeventdata/petrarch#75]
Seems to be a bug that causes PETR to crash. Traceback is:

```
Traceback (most recent call last):
  File "/home/data/phoenix_pipeline/pipeline.py", line 133, in <module>
    run_filter=file_details.oneaday_filter)
  File "/home/data/phoenix_pipeline/pipeline.py", line 98, in main
    config='petr_config.ini')
  File "/usr/local/lib/python2.7/dist-packages/petrarch/petrarch.py", line 3035, in run_pipeline
    updated_events = do_coding(events, 'TEMP')
  File "/usr/local/lib/python2.7/dist-packages/petrarch/petrarch.py", line 2842, in do_coding
    coded_events = code_record()
  File "/usr/local/lib/python2.7/dist-packages/petrarch/petrarch.py", line 2680, in code_record
    assign_NEcodes()
  File "/usr/local/lib/python2.7/dist-packages/petrarch/petrarch.py", line 2376, in assign_NEcodes
    result = check_NEphrase(nephrase)
  File "/usr/local/lib/python2.7/dist-packages/petrarch/petrarch.py", line 2006, in check_NEphrase
    actorcode = get_actor_code(patlist[index][0])
  File "/usr/local/lib/python2.7/dist-packages/petrarch/petrarch.py", line 1883, in get_actor_code
    codelist = PETRglobals.ActorCodes[index]
IndexError: list index out of range
```

@philip-schrodt

**Comment by philip-schrodt** [comment]
Assuming it passes tests with the Phoenix inputs, the changes to the multi-word verb processing I just posted should correct this

**Comment by AroMorin** [comment]
Hello, I am facing the same issue, though I am using Petr on its own (not through PHO). Any ideas?

**Comment by johnb30** [comment]
@AroMorin Which release version are you using? I haven't seen this one pop up in awhile.

**Comment by AroMorin** [comment]
I’m using the “latest” version, just done a fresh install of Petr….An older setup is working fine. My theory is something you changed reintroduced the bug?

**Comment by johnb30** [comment]
Could you paste the full traceback for the error? 

@cnnorris Any thoughts on this?

**Comment by AroMorin** [comment]
Sure! Here's a screenshot of the traceback:



Thanks!!
​

**Comment by johnb30** [comment]
@AroMorin There's no screenshot attached. A copy-paste would also be fine.

**Comment by AroMorin** [comment]
![petr_error](https://cloud.githubusercontent.com/assets/11337560/9176322/ac30bf58-3f58-11e5-8309-5587686a2a4c.png)

**Comment by johnb30** [comment]
What's the command you're using to run the program? Also, a sample of the text you're using would be helpful.

My guess is that you're trying to run unparsed text through the program and it's not currently setup to do that.
